[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
